# Generated by Django 3.2 on 2021-05-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=50),
        ),
    ]
