# Generated by Django 3.2 on 2021-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0002_auto_20210502_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
