# Generated by Django 3.2 on 2021-05-03 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0003_alter_jobcard_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='tracking_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
