# Generated by Django 3.2 on 2021-05-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0004_jobcard_tracking_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='tracking_link',
        ),
    ]
