# Generated by Django 3.2 on 2021-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0007_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
