# Generated by Django 3.2 on 2021-05-04 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0008_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='replay',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
