# Generated by Django 3.2 on 2021-05-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0009_tickets_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='replay',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
