# Generated by Django 3.2 on 2021-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0011_tickets_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='attachments',
            field=models.FileField(blank=True, upload_to='replay_attachments'),
        ),
    ]
