# Generated by Django 3.2 on 2021-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshope', '0013_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
